# Generated by Django 5.1.7 on 2025-03-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_course_menuitems_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='name',
            new_name='item_name',
        ),
    ]
