# Generated by Django 5.1.7 on 2025-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_logger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('count', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
